[build]
builder = "nixpacks"

[deploy]
startCommand = "python working_app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "."
FLASK_ENV = "production"
