services:
  - type: web
    name: barzin-crypto-full
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        value: "crypto_bot_secret_key_for_render"
    healthCheckPath: /
    plan: free